#!/usr/bin/env python3
"""
Combine the Wikipedia frequency list (which Devanagari words to ship)
with Aksharantar pairs (the romanization variants for each word) and
emit BundleResources/system_dict.tsv in the format the IME consumes:

    roman_input<TAB>devanagari_output<TAB>frequency

Stops once --target-words distinct Devanagari headwords have been
written. Words in the frequency list that have no Aksharantar
coverage are skipped and counted at the end (so we can decide later
whether to add an IndicXlit gap-filler step).
"""
import argparse
import sys
import unicodedata
from collections import defaultdict
from pathlib import Path


HEADER_LINES = [
    "# NepaliIME system dictionary — generated by scripts/corpus pipeline",
    "# Source: Aksharantar (AI4Bharat) for romanizations,",
    "#         Nepali Wikipedia frequency list for ranking.",
    "# Format: roman_input<TAB>devanagari_output<TAB>frequency",
    "# Multiple roman spellings per output are intentional (typing-style variance).",
]


def load_frequencies(path: Path) -> list[tuple[str, int]]:
    rows = []
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) != 2:
                continue
            try:
                rows.append((parts[0], int(parts[1])))
            except ValueError:
                continue
    return rows


def load_aksharantar(path: Path) -> dict[str, set[str]]:
    out: dict[str, set[str]] = defaultdict(set)
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.rstrip("\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) != 2:
                continue
            deva = unicodedata.normalize("NFC", parts[0])
            roman = parts[1].strip().lower()
            if deva and roman:
                out[deva].add(roman)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--work-dir", type=Path, default=Path("work/corpus"))
    ap.add_argument(
        "--out", type=Path,
        default=Path("BundleResources/system_dict.tsv"),
    )
    ap.add_argument("--target-words", type=int, default=30000,
                    help="Stop after N distinct Devanagari headwords.")
    args, _unknown = ap.parse_known_args()

    freq_path = args.work_dir / "frequencies.tsv"
    aks_path = args.work_dir / "aksharantar_nep.tsv"
    if not freq_path.exists():
        raise SystemExit(f"missing {freq_path} — run fetch_wiki_freq.py first")
    if not aks_path.exists():
        raise SystemExit(f"missing {aks_path} — run fetch_aksharantar.py first")

    print(f"[build] loading {freq_path}")
    frequencies = load_frequencies(freq_path)
    print(f"[build] {len(frequencies):,} ranked Devanagari words")

    print(f"[build] loading {aks_path}")
    aks = load_aksharantar(aks_path)
    print(f"[build] {len(aks):,} Devanagari headwords with Aksharantar pairs")

    rows: list[tuple[str, str, int]] = []
    headwords_emitted = 0
    miss_count = 0
    for deva, count in frequencies:
        if headwords_emitted >= args.target_words:
            break
        deva_n = unicodedata.normalize("NFC", deva)
        variants = aks.get(deva_n)
        if not variants:
            miss_count += 1
            continue
        for roman in variants:
            rows.append((roman, deva_n, count))
        headwords_emitted += 1

    rows.sort(key=lambda r: (-r[2], r[0]))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8") as fh:
        for line in HEADER_LINES:
            fh.write(line + "\n")
        fh.write("\n")
        for roman, deva, freq in rows:
            fh.write(f"{roman}\t{deva}\t{freq}\n")

    print(f"[build] wrote {len(rows):,} rows "
          f"({headwords_emitted:,} headwords) to {args.out}")
    if miss_count:
        print(f"[build] {miss_count:,} ranked words had no Aksharantar coverage "
              "(skipped — would need IndicXlit gap-fill to recover)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
